variables:
  colors:
    primaryColor1: 3A3A3A
    primaryColor2: 5A5A5A
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
  fonts:
    defaultHeaderFont: georgia
    defaultBodyFont: helvetica
features:
  node_user_picture: false
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
logo:
  use_default: true
  path: ''
favicon:
  use_default: true
  path: ''
omega_toggle_intro: 0
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 0
screen_demo_indicator: 1
default_layout: primary
home_layout: front
enable_omegags_layout: 0
layouts: {  }
breakpoint_group_primary: omega_samhsa_test_two.default
breakpoint_group_front: omega_samhsa_test_two.default
edit_this_layout: primary
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_tags_layout: primary
_core:
  default_config_hash: 9e1gQsGrM0X5Hkrubl9Dqm11NhuSHDYtLg3sBpoLNUg
compile_scss: 0
show_compile_warning: 0
enable_omega_badge: 0
styles:
  omega_samhsa_test_two/omega_samhsa_test_two: 1
  omega/omega: 1
  omega/omega_html_elements: 0
  omega/omega_branding: 0
  omega/omega_breadcrumbs: 0
  omega/omega_main_menus: 0
  omega/omega_messages: 0
  omega/omega_pagers: 0
  omega/omega_tabs: 0
  omega/omega_taxonomy_terms: 0
  omega/omega_forms: 0
  omega_samhsa/omega_samhsa: 1
layout-config:
  non_omegags_info: ''
