<?php

use Drupal\samhsa_gpo\API\SamhsaGpoAPI;

function samhsa_gpo_cron() {
  $date = date("Y-m-d", strtotime("yesterday"));

  // Export Special Requests if any
  $exportExists = SamhsaGpoAPI::testForExport($date, 'special_request');
  if (!$exportExists) {
    SamhsaGpoAPI::generateXML($date,'special_request');
  }

  // Export regular orders
  $exportExists = SamhsaGpoAPI::testForExport($date, 'all');
  if (!$exportExists) {
    SamhsaGpoAPI::generateXML($date, 'all');
  }
}
