samhsa_pep_password.settings:
  type: config_object
  label: 'SAMHSA PEP Password control settings'
  mapping:
    length_enforce:
      type: boolean
      label: 'Enforce minimum password length'
    length_min_user:
      type: integer
      label: 'Minimum password length for common users'
    length_min_admin:
      type: integer
      label: 'Minimum password length for privileged users'
    character_enforce:
      type: boolean
      label: 'Enforce character classes'
    character_upper_min:
      type: integer
      label: 'Minimum number of Uppercase characters'
    character_lower_min:
      type: integer
      label: 'Minimum number of Lowercase characters'
    character_numeric_min:
      type: integer
      label: 'Minimum number of Numeric characters'
    character_special_min:
      type: integer
      label: 'Minimum number of Special characters'
    lifetime_min_enforce:
      type: boolean
      label: 'Enforce Minimum password lifetime'
    lifetime_min:
      type: integer
      label: 'Minimum password lifetime (days)'
    lifetime_max_enforce:
      type: boolean
      label: 'Enforce Maximum password lifetime'
    lifetime_max:
      type: integer
      label: 'Maximum password lifetime (days)'
    password_reuse_enforce:
      type: boolean
      label: 'Enforce password reuse restriction'
    password_reuse_count:
      type: integer
      label: 'Minimum number of unique passwords'
    password_pattern_enforce:
      type: boolean
      label: 'Restrict reuse of same characters between passwords'
    password_pattern_yield:
      type: integer
      label: 'Maximum percentage of identical characters in same location'
    cron_threshold:
      type: integer
      label: 'Maximum number of users to expire in a single cron pass'
    admin_roles:
      type: sequence
      label: 'User roles for stricter password length control'
      sequence:
        type: string
