<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function samhsa_pep_justification_pane_help($route_name, RouteMatchInterface $route_match): string {
  $output = '';
  switch ($route_name) {
    // Main module help for the samhsa_pep_justification_pane module.
    case 'help.page.samhsa_pep_justification_pane':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define SAMHSA PEP Justification Pane.') . '</p>';

    default:
  }

  return $output;
}

/**
 * Prepares variables for order templates.
 *
 * Default template: commerce-order.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function samhsa_pep_justification_pane_preprocess_commerce_order(array &$variables): void {
  /** @var Drupal\commerce_order\Entity\OrderInterface $order */
  $order = $variables['elements']['#commerce_order'];
  $justification = $order->get('field_justification')->value ?? '';
  $variables['order']['justification'] = $justification;
}
