<?php

/**
 * @file
 * Contains migrate_files_and_images.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_files_and_images_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_files_and_images module.
    case 'help.page.migrate_files_and_images':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate the managed files') . '</p>';
      return $output;

    default:
  }
}
