<?php

/**
 * @file
 * Contains samhsa_pep_mail.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements send_email method.
 */
function send_mail(EntityInterface $entity, $module, $action, $subject, $message, $title, $to, $show_msg = TRUE) {
    //$mailManager = \Drupal::service('plugin.manager.mail');
    $key = $action;

    if (isset($to) && strlen(trim($to)) > 0) {
        $params['message'] = $message;
        $params['subject'] = $subject;
        $from = \Drupal::config('system.site')->get('mail');
        $headers = array();
        $headers['Content-Type'] =  'text/plain; charset=UTF-8; format=flowed; delsp=yes';
        $headers['Content-Transfer-Encoding'] =  '8Bit';
        $headers['Sender'] =  $from;
        $headers['From'] =  $from;

        $langcode = \Drupal::currentUser()->getPreferredLangcode();
        $send = TRUE;
        $result = \Drupal::service('plugin.manager.mail')->mail(
            $module,
            $key,
            $to,
            $langcode,
            array(
                'from' => $from,
                'reply-to' => $from,
                'subject' => $subject,
                'body' => $message,
                //'headers' => $headers,
            ),
            FALSE,
            TRUE
        );

        if ($result['result'] !== TRUE) {
            \Drupal::messenger()->addError(t('There was a problem sending your message and it was not sent.'));
        } else {
            $message = t('Order status updates has been sent to @email ', array('@email' => $to));
            \Drupal::logger('mail-log')->notice($message);
        if($show_msg) {
            \Drupal::messenger()->addMessage(t('You will be receiving an email confirmation on your order status.'));
        }

        }
    }
}

/**
 * Implements hook_theme().
 */
function samhsa_pep_mail_theme($existing, $type, $theme, $path) {
    return [
        'commerce_order_receipt' => [
            'template' => 'samhsa-pep-mail-order-receipt',
            'base hook' => 'commerce_order_receipt',
        ],
    ];
}