<?php

/**
 * @file
 * Jbs_commerce_over_the_max_limit.install.
 */

/**
 * Implements hook_install().
 */
function samhsa_pep_daily_prod_report_download_install() {
  // Save default configs.
  // $config = \Drupal::service('config.factory')->getEditable('samhsa_pep_daily_prod_report_download.settings');.
}

/**
 * Implements hook_uninstall().
 */
function samhsa_pep_daily_prod_report_download_uninstall() {
  Drupal::configFactory()->getEditable('samhsa_pep_daily_prod_report_download.settings')->delete();
}
