<?php

/**
 * @file
 * Contains samhsa_publications_inventory_ex.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function samhsa_publications_inventory_ex_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the samhsa_publications_inventory_ex module.
    case 'help.page.samhsa_publications_inventory_ex':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Samhsa Publications Inventory and Storage Status') . '</p>';
      return $output;

    default:
  }
}
